### ISSUE TITLE
Strange shape on the back of the head

### ISSUE THREAD

**Issue by blx0102** [philgras/neural-head-avatars#10]
Hi, I tried the person_0000 data for Avatar Optimization, all setting were remained except gpus=1. 
But there is strange sharp shape on the back of the head, is that normal? 
I'll try my own data next step, how can I avoid this? Should I add some video data about the back of head to my data as well?

![image](https://user-images.githubusercontent.com/17761044/168942265-09e42f32-6517-4266-94a0-e8e37fcb4eb7.png)

**Comment by wengjincheng** [comment]
Hi, How can you run the pip install -e . success, I can't download the pytorch3d using the https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1100/pytorch3d-0.6.1-cp39-cp39-linux_x86_64.whl?

**Comment by blx0102** [comment]
@philgras Got it, thanks for your reply!

**Comment by blx0102** [comment]
@wengjincheng Actually I've already have pytorch3d installed before try this repo, I think I used the command like below:

pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html

**Comment by icegaomu** [comment]
> Hi, I tried the person_0000 data for Avatar Optimization, all setting were remained except gpus=1. But there is strange sharp shape on the back of the head, is that normal? I'll try my own data next step, how can I avoid this? Should I add some video data about the back of head to my data as well?
> 
> ![image](https://user-images.githubusercontent.com/17761044/168942265-09e42f32-6517-4266-94a0-e8e37fcb4eb7.png)

hello, i want to know how can you save the mesh after offset the fair ,i don't find those codes .Thanks a lot!

**Comment by icegaomu** [comment]
@blx0102  can you give me some help?
