### ISSUE TITLE
The dependencies can not download

### ISSUE THREAD

**Issue by wengjincheng** [philgras/neural-head-avatars#11]
My python version is 3.9.12

When I run this command: pip install -e .

There is an error: ERROR: HTTP error 403 while getting https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1100/pytorch3d-0.6.1-cp39-cp39-linux_x86_64.whl

**Comment by philgras** [comment]
Hi, please have a look at #7 . The reason for the problem is that the prebuild wheel of pytroch3d no longer is available. Unless you build from source, you need to install the available pytorch3d wheel and the matching pytorch version.

Hope this helps!

**Comment by thesujitroy** [comment]
Hi,
Please change 
"pytorch3d@https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1100/pytorch3d-0.6.1-cp39-cp39-linux_x86_64.whl"
in the setup file 
to 
"pytorch3d@https://github.com/thesujitroy/pytorch3d/raw/main/pytorch3d-0.6.1-cp39-cp39-linux_x86_64.whl",

and it should work
