### ISSUE TITLE
ModuleNotFoundError: No module named 'InsightFace.recognition'

### ISSUE THREAD

**Issue by wengjincheng** [philgras/neural-head-avatars#13]
Hi,

I followed the guide of the readme.
complete the install guide.

when I run quickstart, something wrong:

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [5], in <cell line: 5>()
      3 from nha.util.render import create_intrinsics_matrix
      4 import torch
----> 5 from nha.models.nha_optimizer import NHAOptimizer
      6 from nha.util.general import dict_2_device
      7 import numpy as np

File ~/neural-head-avatars/nha/models/__init__.py:1, in <module>
----> 1 from . import nha_optimizer
      3 str2model = dict(NHAOptimizer=nha_optimizer.NHAOptimizer)

File ~/neural-head-avatars/nha/models/nha_optimizer.py:6, in <module>
      4 from nha.models.texture_mlp import NormalEncoder, TextureMLP
      5 from nha.optimization.criterions import LeakyHingeLoss, MaskedCriterion
----> 6 from nha.optimization.perceptual_loss import ResNetLOSS
      7 from nha.optimization.holefilling_segmentation_loss import calc_holefilling_segmentation_loss
      8 from nha.data.real import CLASS_IDCS, digitize_segmap

File ~/neural-head-avatars/nha/optimization/perceptual_loss.py:12, in <module>
      9 from pathlib import Path
     11 sys.path.append(str((Path(__file__).parents[2]/"deps")))
---> 12 from InsightFace.recognition.arcface_torch.backbones import get_model
     15 class VGG16(torch.nn.Module):
     16     def __init__(self, requires_grad=False):

ModuleNotFoundError: No module named 'InsightFace.recognition'`

I have installed InsightFace 0.6.2, I can't find the recognition submodule, can you tell me which version is preferred?

Thanks

**Comment by wengjincheng** [comment]
Oh, It's a submodule. I will close it.

**Comment by lskdream** [comment]
@wengjincheng Can I know where you found this submodule?

**Comment by carlosedubarreto** [comment]
@lskdream 
correcting....
if you use on windows maybe you will run into the sme problem as me.

pip install Cython
then run 
pip install insightface

**Comment by HaoZhang990127** [comment]
@lskdream 

you can find the submodel links in deps folder and you can clone them by yourself to the deps folder to overcome the No module error
