### ISSUE TITLE
There are no file optimize_avatar.py  in the folder python_scripts

### ISSUE THREAD

**Issue by chenlinjia** [philgras/neural-head-avatars#15]
the command: python python_scripts/optimize_avatar.py --config configs/avatar_optimization.ini
optimize_avatar.py file is not in the folder, is this reenact_avatar.py or Missing File?

**Comment by dipesh-commits** [comment]
You need to use optimize_nha.py file instead of optimize_avatar.py. May be there is some typo while they create the command. I have used it  and it is working fine.

**Comment by philgras** [comment]
Hi, the readme has been updated. optimize_nha.py is the correct file.
