### ISSUE TITLE
neural-head-avatars/deps/RobustVideoMatting/model/decoder.py", line 169, in forward_single_frame     r, z = self.ih(torch.cat([x, h], dim=1)).split(self.channels, dim=1) RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 18 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by jinfagang** [philgras/neural-head-avatars#2]
neural-head-avatars/deps/RobustVideoMatting/model/decoder.py", line 169, in forward_single_frame
    r, z = self.ih(torch.cat([x, h], dim=1)).split(self.channels, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 18 for tensor number 1 in the list.

**Comment by philgras** [comment]
I've tried to reproduce this but it doesn't show up for different videos I tested. Providing more details on how you encountered it would be helpful.

**Comment by jinfagang** [comment]
@philgras it might be happend when somehow 2 heads detected. There might no such handling in code.

**Comment by jinfagang** [comment]
@philgras it is. I would suggest if we can handle it or put some warnings to reminder user would be more friendly for newcomers. thanks for your clarification though.
