### ISSUE TITLE
Another problem when run optimize_tracking.py

### ISSUE THREAD

**Issue by yangohuang** [philgras/neural-head-avatars#23]
hello, thanks for your contribution!
I met a problem when I run python deps/video-head-tracker/vht/optimize_tracking.py --config configs/tracking.ini, the log is as below:

Traceback (most recent call last):
  File "/data/yango/code/neural-head-avatars/deps/video-head-tracker/vht/optimize_tracking.py", line 59, in <module>
    main()
  File "/data/yango/code/neural-head-avatars/deps/video-head-tracker/vht/optimize_tracking.py", line 54, in main
    tracker = Tracker(data, **args_dict)
  File "/data/yango/code/neural-head-avatars/deps/video-head-tracker/vht/model/tracking.py", line 128, in __init__
    self._flame_tex.to(device)
  File "/home/zego/anaconda3/envs/nerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/home/zego/anaconda3/envs/nerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 625, in _apply
    self._buffers[key] = fn(buf)
  File "/home/zego/anaconda3/envs/nerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 0; 9.78 GiB total capacity; 28.89 MiB already allocated; 144.88 MiB free; 46.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

in which I create my own dataset from a self-made video, and when I run optimize_tracking I met this problem~ Any suggestions, thanks~

**Comment by yangohuang** [comment]
`[dataset]
data_path = 'linwei/'

[model]
n_shape = 300
n_expr = 100
n_tex = 100
tex_res = 512

[training]
device = cuda
output_path = output
calibrated = false
ignore_lower_neck = true
img_log_freq = 50
energy_log_freq = 5

keyframes = [0, 110, 150, 200, 265, 300, 380, 500, 640, 735, 812, 875, 917]
; keyframes =[300]
[hyper params]
init_steps = 400
steps_per_frame = 10
sub_steps = 5
lr = 0.005
pos_lr = 0.001
light_lr = 0.005
cam_lr = 0.005

blur_sigma = [10, 1e-4]
sampling_scale = 4

w_lmk = 5
w_eyes_sym = 10
w_eyes_lmk = 2
w_photo = 30

w_expr_reg = 1e-3
w_shape_reg = 1e-3
w_tex_reg = 1e-3

w_pos_glob = 1e-2
w_pos_neck = 1e-2
w_pos_jaw = 1e-4
w_pos_eyes = 1e-4
w_pos_trans = 10
`

**Comment by Dratlan** [comment]
I have experiment it in a RTX3090(memory 24GB) and a RTX 2080Ti(memory 11GB), the latter came out with cuda out of memory, so my answer is enlarge your memory(like RTX3090, and it takes near 18GB to run). Or, you can use a smaller Monocular RGB Videos in lower resolution and less time(less frame).(I use the video in the paper, it's a little bigger) I tried to figure out the max_split_size_mb, I think that does'nt work.

**Comment by philgras** [comment]
Hi,

Thanks a lot for your interest in our work. If you run into memory problems when running the tracking script, you have basically three options to reduce the memory footprint.
1. Use less key frames
2. Reduce video resolution (there is actually a command line parameter for this, if you dont want to do it yourself)
3. Set sampling_scale to a lower value (not smaller than 1). This parameter multiplied with the input video resolution is the effective resolution used in the photometric term for optimization. With a higher sampling scale, the tracking often becomes smoother. However, you can reduce it to save memory.

Hope this helps!
