### ISSUE TITLE
Mesh output

### ISSUE THREAD

**Issue by sidk99** [philgras/neural-head-avatars#25]
Thanks for the great work! How can the offsets used to generate the optimized mesh be saved/exported as an obj?

**Comment by icegaomu** [comment]
Hi ，do you save the problem ?
I have some suggest in the   nha_optimaizer.py

```
# FILL SCENE
        cameras = create_camera_objects(K, RT, (H, W), self.device)
        flame_meshes = Meshes(verts=verts, faces=self._flame.faces[None].expand(len(verts), -1, -1))


        io = IO()
        io.save_mesh(data=flame_meshes, path='test.obj')
```
This will save the offset mesh 
And i have another question about how to save the texture and RASTERIZING  in 3d?Do you know?

**Comment by philgras** [comment]
Hi,
I proposed a solution in #30 . Hope this helps! Feel free to reopen or comment in #30.
