### ISSUE TITLE
optimize_tracking.py: error: the following arguments are required: --tracking_resolution

### ISSUE THREAD

**Issue by jinfagang** [philgras/neural-head-avatars#3]
optimize_tracking.py: error: unrecognized arguments: --load_lmk=true --load_seg=true --add_teeth=True --bone_lr=0.001 --w_eyes_closed=0

I so confused in your code reproduce, so many bugs.

**Comment by philgras** [comment]
Sorry! Apparently, I put an old tracking.ini file into the configs folder. I updated the config file and the README. Let me know if you still face problems.

**Comment by jinfagang** [comment]
thanks, it now worked!
