### ISSUE TITLE
tracking result not right

### ISSUE THREAD

**Issue by jinfagang** [philgras/neural-head-avatars#4]
Hi, the tracking visual seems abnormal, can u pointed my out why/

I set the tracking resolution to 512x512

![image](https://user-images.githubusercontent.com/21303438/165234807-15861a77-49bf-433a-b47f-1a9da408f73c.png)

**Comment by philgras** [comment]
Hi, sorry for the confusion. The parameter `tracking_resolution` should match the aspect ratio of the input frames. It seems like your frames are not squared but rectangular (landscape).  If you have enough GPU memory resources and want to track in full resolution you can just set it to pixel `height, width` of your frames.
One remark: For better preprocessing outputs, I would recommend choosing a tighter crop around the head of the subject.
I updated the README accordingly and added some additional recommendations for using custom videos. Thanks!

**Comment by jinfagang** [comment]
@philgras Hi, I have some suggestions, if it need keep ratio, then just let users set ratio, rather than w,h, since we can calculate w,h from original frame. it was much more robust, also users can shrink down the ratio if GPU resource limited.

For the remark, this image is already output of first step, it actually does face alignment and keypoint detection, why not direcly crop it in first step so that users don't need manually or intentionly find some videos which head much be lower in frame?

**Comment by jinfagang** [comment]
thank u for your detailed explaination. I will help test more video if I can make it fully run.
