### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by neerajtiwari360** [philgras/neural-head-avatars#48]
I made the docker setup for this project package requirements here>>> docker pull neerajtiwari0007/nha:0.2
Enjoy!

**Comment by edhyah** [comment]
Newb question, how can I use this @neerajtiwari360 ? 

I ran `docker run -it neerajtiwari0007/nha:0.2 /bin/bash`. What do I do next? git clone the repo and install all of the dependencies again?

In other words, how do I run the code after docker pull? Thanks!
