### ISSUE TITLE
tracking wrong

### ISSUE THREAD

**Issue by jinfagang** [philgras/neural-head-avatars#6]
![image](https://user-images.githubusercontent.com/21303438/165503731-f61a52ce-7aab-4bb4-9166-5db1fa38ea8d.png)

I have edit tracking resolution to hw

**Comment by philgras** [comment]
Hi, I was able to reproduce this. There was an error that confused height and width during rendering of rectangular images.
You can pull the fix from the submodule under `deps/ video-head-tracker `. I tested it for both landscape and profile formats.
![image](https://user-images.githubusercontent.com/13590652/165779408-865a5548-3b5e-4b7d-826f-a170bd8c5ffc.png)
![image](https://user-images.githubusercontent.com/13590652/165779598-1c87fcd0-db60-4922-946b-cc45942b7678.png)

**Comment by jinfagang** [comment]
@philgras wao, thank u! BTW, why the recovered perception look doens't quit look as original?

**Comment by philgras** [comment]
Hi, the loss of personal details in the appearance is influenced by multiple factors. The most dominant one is that the optimized texture is simply a low dimensional vector in the statistical [FLAME texture space](https://github.com/HavenFeng/photometric_optimization) which was formed via PCA over 1500 fitted texture maps. So, don't expect many individual details to be reproduced, especially eye colors and wrinkles seem to be a problem. Still, for tracking the expressions and poses, it is sufficient.

**Comment by jinfagang** [comment]
@philgras thank u! I will share a primilary result once I trained. BTW, why the optimization way to NHA reconstruction so slow, does there any learning base solution of this?
